# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: 'Build and Push the Docker image to ACR'
  inputs:
    containerRegistry: 'pallavdevops_acr'
    repository: 'nodeapp'
    command: 'buildAndPush'
    Dockerfile: '**/app/Dockerfile'
    tags: |
      1.0
- task: Kubernetes@1
  displayName: 'Deploy the K8s Deployment with the pushed image'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'learningk8s'
    namespace: 'pallav'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/home/vsts/work/1/s/manifests/nodeapp.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'