apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodeapp-hpa
  namespace: pallav
spec:
  maxReplicas: 3 # define max replica count
  minReplicas: 1  # define min replica count
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodeapp
  targetCPUUtilizationPercentage: 50 # target CPU utilization