  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nodeapp
    namespace: pallav
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: nodeapp
    template:
      metadata:
        labels:
          app: nodeapp
      spec:
        containers:
          - name: nodeapp
            image: pallavdevops.azurecr.io/nodeapp:1.0
            env:
              - name: ENV
                value: 'dev'
            resources:
              requests:
                cpu: 120m
                memory: 128Mi
              limits:
                cpu: 250m
                memory: 256Mi
            ports:
              - containerPort: 3000
                name: node
